repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: generate-markdown
        name: Generate Markdown
        entry: python C:/Users/joneh/master_thesis/data/database/gen_md.py
        language: system
        files: '^db_status\.md$'
        stages: [pre-commit]
