BASE:
  - 'REALIZED_VOL'
  - 'CLOSE'
  - 'VOLUME'
  - 'COUNT'
  - 'LOGRET'
TEMPORAL:
  - 'HOUR'
  - 'MINUTE'
  - 'DAY_OF_WEEK'
  - 'DAY_OF_MONTH'
  - 'MONTH'
  - 'YEAR'
SENTIMENT:
  - 'CRU_TextBlob'
  - 'CRU_VADER'
  - 'CWP_TextBlob'
  - 'CWP_VADER'
  - 'CEN_TextBlob'
  - 'CEN_VADER'
  - 'CRU_1_TextBlob'
  - 'CRU_1_VADER'
  - 'CRU_2_TextBlob'
  - 'CRU_2_VADER'
  - 'CRU_0_TextBlob'
  - 'CRU_0_VADER'
  - 'CWP_0_TextBlob'
  - 'CWP_0_VADER'
  - 'CWP_1_TextBlob'
  - 'CWP_1_VADER'
  - 'CWP_2_TextBlob'
  - 'CWP_2_VADER'
  - 'CEN_2_TextBlob'
  - 'CEN_2_VADER'
  - 'CEN_0_TextBlob'
  - 'CEN_0_VADER'
  - 'CEN_1_TextBlob'
  - 'CEN_1_VADER'
  - 'CT_1_TextBlob'
  - 'CT_1_VADER'
  - 'CT_0_TextBlob'
  - 'CT_0_VADER'
  - 'CT_4_TextBlob'
  - 'CT_4_VADER'
  - 'CT_2_TextBlob'
  - 'CT_2_VADER'
  - 'CT_3_TextBlob'
  - 'CT_3_VADER'
  - 'CRU_TextBlob_SI'
  - 'CRU_VADER_SI'
  - 'CWP_TextBlob_SI'
  - 'CWP_VADER_SI'
  - 'CEN_TextBlob_SI'
  - 'CEN_VADER_SI'
  - 'CRU_1_TextBlob_SI'
  - 'CRU_1_VADER_SI'
  - 'CRU_2_TextBlob_SI'
  - 'CRU_2_VADER_SI'
  - 'CRU_0_TextBlob_SI'
  - 'CRU_0_VADER_SI'
  - 'CWP_0_TextBlob_SI'
  - 'CWP_0_VADER_SI'
  - 'CWP_1_TextBlob_SI'
  - 'CWP_1_VADER_SI'
  - 'CWP_2_TextBlob_SI'
  - 'CWP_2_VADER_SI'
  - 'CEN_2_TextBlob_SI'
  - 'CEN_2_VADER_SI'
  - 'CEN_0_TextBlob_SI'
  - 'CEN_0_VADER_SI'
  - 'CEN_1_TextBlob_SI'
  - 'CEN_1_VADER_SI'
  - 'CT_1_TextBlob_SI'
  - 'CT_1_VADER_SI'
  - 'CT_0_TextBlob_SI'
  - 'CT_0_VADER_SI'
  - 'CT_4_TextBlob_SI'
  - 'CT_4_VADER_SI'
  - 'CT_2_TextBlob_SI'
  - 'CT_2_VADER_SI'
  - 'CT_3_TextBlob_SI'
  - 'CT_3_VADER_SI'
SENT_TP:
  - 'CRU_TextBlob_SI'
  - 'CRU_VADER_SI'
  - 'CWP_TextBlob_SI'
  - 'CWP_VADER_SI'
  - 'CEN_TextBlob_SI'
  - 'CEN_VADER_SI'
SENT_IT:
  - 'CRU_1_TextBlob_SI'
  - 'CRU_1_VADER_SI'
  - 'CRU_2_TextBlob_SI'
  - 'CRU_2_VADER_SI'
  - 'CRU_0_TextBlob_SI'
  - 'CRU_0_VADER_SI'
  - 'CWP_0_TextBlob_SI'
  - 'CWP_0_VADER_SI'
  - 'CWP_1_TextBlob_SI'
  - 'CWP_1_VADER_SI'
  - 'CWP_2_TextBlob_SI'
  - 'CWP_2_VADER_SI'
  - 'CEN_2_TextBlob_SI'
  - 'CEN_2_VADER_SI'
  - 'CEN_0_TextBlob_SI'
  - 'CEN_0_VADER_SI'
  - 'CEN_1_TextBlob_SI'
  - 'CEN_1_VADER_SI'
SENT_CT:
  - 'CT_1_TextBlob_SI'
  - 'CT_1_VADER_SI'
  - 'CT_0_TextBlob_SI'
  - 'CT_0_VADER_SI'
  - 'CT_4_TextBlob_SI'
  - 'CT_4_VADER_SI'
  - 'CT_2_TextBlob_SI'
  - 'CT_2_VADER_SI'
  - 'CT_3_TextBlob_SI'
  - 'CT_3_VADER_SI'
SELECTED_5:
  - 'CWP_2_TextBlob_SI'
  - 'CWP_1_TextBlob_SI'
  - 'CWP_2_TextBlob_SI'
  - 'CT_0_TextBlob_SI'
  - 'CT_3_TextBlob_SI'
  - 'CWP_TextBlob_SI'
VAR_TOPICS:
  - 'REALIZED_VOL'
  - 'CRU_TextBlob'
  - 'CRU_VADER'
  - 'CWP_TextBlob'
  - 'CWP_VADER'
  - 'CEN_TextBlob'
  - 'CEN_VADER'
  - 'CRU_1_TextBlob'
  - 'CRU_1_VADER'
  - 'CRU_2_TextBlob'
  - 'CRU_2_VADER'
  - 'CRU_0_TextBlob'
  - 'CRU_0_VADER'
  - 'CWP_0_TextBlob'
  - 'CWP_0_VADER'
  - 'CWP_1_TextBlob'
  - 'CWP_1_VADER'
  - 'CWP_2_TextBlob'
  - 'CWP_2_VADER'
  - 'CEN_2_TextBlob'
  - 'CEN_2_VADER'
  - 'CEN_0_TextBlob'
  - 'CEN_0_VADER'
  - 'CEN_1_TextBlob'
  - 'CEN_1_VADER'
  - 'CT_0_TextBlob'
  - 'CT_0_VADER'
  - 'CT_1_TextBlob'
  - 'CT_1_VADER'
  - 'CT_2_TextBlob'
  - 'CT_2_VADER'
  - 'CT_3_TextBlob'
  - 'CT_3_VADER'
  - 'CT_4_TextBlob'
  - 'CT_4_VADER'
VAR_TOPICS_BASE:
  - 'CRU_TextBlob'
  - 'CRU_VADER'
  - 'CWP_TextBlob'
  - 'CWP_VADER'
  - 'CEN_TextBlob'
  - 'CEN_VADER'
VAR_TOPICS_IT:
  - 'CRU_1_TextBlob'
  - 'CRU_1_VADER'
  - 'CRU_2_TextBlob'
  - 'CRU_2_VADER'
  - 'CRU_0_TextBlob'
  - 'CRU_0_VADER'
  - 'CWP_0_TextBlob'
  - 'CWP_0_VADER'
  - 'CWP_1_TextBlob'
  - 'CWP_1_VADER'
  - 'CWP_2_TextBlob'
  - 'CWP_2_VADER'
  - 'CEN_2_TextBlob'
  - 'CEN_2_VADER'
  - 'CEN_0_TextBlob'
  - 'CEN_0_VADER'
  - 'CEN_1_TextBlob'
  - 'CEN_1_VADER'
VAR_TOPICS_CT:
  - 'CT_0_TextBlob'
  - 'CT_0_VADER'
  - 'CT_1_TextBlob'
  - 'CT_1_VADER'
  - 'CT_2_TextBlob'
  - 'CT_2_VADER'
  - 'CT_3_TextBlob'
  - 'CT_3_VADER'
  - 'CT_4_TextBlob'
  - 'CT_4_VADER'
TOPICS_BASE:
  - 'CRU'
  - 'CWP'
  - 'CEN'
TOPICS_IT:
  - 'CRU_0'
  - 'CRU_1'
  - 'CRU_2'
  - 'CWP_0'
  - 'CWP_1'
  - 'CWP_2'
  - 'CEN_0'
  - 'CEN_1'
  - 'CEN_2'
TOPICS_CT:
  - 'CT_0'
  - 'CT_1'
  - 'CT_2'
  - 'CT_3'
  - 'CT_4'
