BASE:
  - 'CLOSE'
  - 'VOLUME'
  - 'COUNT'
  - 'LOGRET'
  - 'REALIZED_VOL'
TEMPORAL:
  - 'HOUR'
  - 'MINUTE'
  - 'MINUTE_OF_DAY'
  - 'DAY_OF_WEEK'
  - 'DAY_OF_MONTH'
SENTIMENT:
  - 'CRU_TextBlob'
  - 'CRU_VADER'
  - 'CWP_TextBlob'
  - 'CWP_VADER'
  - 'CEN_TextBlob'
  - 'CEN_VADER'
  - 'CRU_1_TextBlob'
  - 'CRU_1_VADER'
  - 'CRU_2_TextBlob'
  - 'CRU_2_VADER'
  - 'CRU_0_TextBlob'
  - 'CRU_0_VADER'
  - 'CWP_0_TextBlob'
  - 'CWP_0_VADER'
  - 'CWP_1_TextBlob'
  - 'CWP_1_VADER'
  - 'CWP_2_TextBlob'
  - 'CWP_2_VADER'
  - 'CEN_2_TextBlob'
  - 'CEN_2_VADER'
  - 'CEN_0_TextBlob'
  - 'CEN_0_VADER'
  - 'CEN_1_TextBlob'
  - 'CEN_1_VADER'
  - 'CT_1_TextBlob'
  - 'CT_1_VADER'
  - 'CT_0_TextBlob'
  - 'CT_0_VADER'
  - 'CT_4_TextBlob'
  - 'CT_4_VADER'
  - 'CT_2_TextBlob'
  - 'CT_2_VADER'
  - 'CT_3_TextBlob'
  - 'CT_3_VADER'
  - 'CRU_TextBlob_SI'
  - 'CRU_VADER_SI'
  - 'CWP_TextBlob_SI'
  - 'CWP_VADER_SI'
  - 'CEN_TextBlob_SI'
  - 'CEN_VADER_SI'
  - 'CRU_1_TextBlob_SI'
  - 'CRU_1_VADER_SI'
  - 'CRU_2_TextBlob_SI'
  - 'CRU_2_VADER_SI'
  - 'CRU_0_TextBlob_SI'
  - 'CRU_0_VADER_SI'
  - 'CWP_0_TextBlob_SI'
  - 'CWP_0_VADER_SI'
  - 'CWP_1_TextBlob_SI'
  - 'CWP_1_VADER_SI'
  - 'CWP_2_TextBlob_SI'
  - 'CWP_2_VADER_SI'
  - 'CEN_2_TextBlob_SI'
  - 'CEN_2_VADER_SI'
  - 'CEN_0_TextBlob_SI'
  - 'CEN_0_VADER_SI'
  - 'CEN_1_TextBlob_SI'
  - 'CEN_1_VADER_SI'
  - 'CT_1_TextBlob_SI'
  - 'CT_1_VADER_SI'
  - 'CT_0_TextBlob_SI'
  - 'CT_0_VADER_SI'
  - 'CT_4_TextBlob_SI'
  - 'CT_4_VADER_SI'
  - 'CT_2_TextBlob_SI'
  - 'CT_2_VADER_SI'
  - 'CT_3_TextBlob_SI'
  - 'CT_3_VADER_SI'
SENTIMENT_CUSTOM:
  - 'CT_1_TextBlob_SI'
  - 'CT_1_VADER_SI'
  - 'CT_0_TextBlob_SI'
  - 'CT_0_VADER_SI'
  - 'CT_4_TextBlob_SI'
  - 'CT_4_VADER_SI'
  - 'CT_2_TextBlob_SI'
  - 'CT_2_VADER_SI'
  - 'CT_3_TextBlob_SI'
  - 'CT_3_VADER_SI'
SENTIMENT_CUSTOM_2:
  - 'CRU_TextBlob_SI'
  - 'CRU_VADER_SI'
  - 'CWP_TextBlob_SI'
  - 'CWP_VADER_SI'
  - 'CEN_TextBlob_SI'
  - 'CEN_VADER_SI'
  - 'CRU_1_TextBlob_SI'
  - 'CRU_1_VADER_SI'
  - 'CRU_2_TextBlob_SI'
  - 'CRU_2_VADER_SI'
  - 'CRU_0_TextBlob_SI'
  - 'CRU_0_VADER_SI'
  - 'CWP_0_TextBlob_SI'
  - 'CWP_0_VADER_SI'
  - 'CWP_1_TextBlob_SI'
  - 'CWP_1_VADER_SI'
  - 'CWP_2_TextBlob_SI'
  - 'CWP_2_VADER_SI'
  - 'CEN_2_TextBlob_SI'
  - 'CEN_2_VADER_SI'
  - 'CEN_0_TextBlob_SI'
  - 'CEN_0_VADER_SI'
  - 'CEN_1_TextBlob_SI'
  - 'CEN_1_VADER_SI'
